export { extractRoutes } from './routeExtractor';
export { generateDoc, generateMarkdown } from './docGenerator';
export { startWatcher, stopWatcher } from './syncWatcher';
export { writeDocumentation, readDocumentation, writeIfChanged } from './outputWriter';
export { routewatch, stopRoutewatch } from './middlewareFactory';
export { validateRoute, validateRoutes } from './schemaValidator';
export { filterRoutes, groupRoutesByPrefix, deduplicateRoutes } from './routeFilter';
export { formatAsJson, formatAsMarkdown, formatAsSummary } from './routeFormatter';
export { compareRoutes, hasRouteChanges, formatDiffSummary } from './routeComparator';
export { setCachedRoutes, getCachedRoutes, isCacheStale, hasCacheChanged } from './routeCache';
export { configureLogger, log, logRoutesDetected, logRouteChanged, logDocumentationWritten } from './routeLogger';
export { exportRoutes } from './routeExporter';
export { runHealthCheck, findDuplicateRoutes, findMissingMethods, findInvalidPaths } from './routeHealthCheck';
export type { RouteInfo } from './types';
export type { HealthCheckResult } from './routeHealthCheck';
